groups:
  - name: integr8scode_alerts
    rules:
      - alert: HighScriptErrorRate
        expr: rate(script_executions_total{status="error"}[5m]) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High script error rate detected
          description: "The rate of script execution errors is above 20% in the last 5 minutes"

      - alert: HighActiveScripts
        expr: active_executions > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High number of active scripts
          description: "More than 5 scripts are running simultaneously"

      - alert: HighPodCreationFailureRate
        expr: rate(pod_creation_failures_total[5m]) > 0.1
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: High pod creation failure rate
          description: "Pod creation failure rate is above 10% in the last 5 minutes (current rate: {{ $value }})"

      - alert: PodCreationImagePullErrors
        expr: rate(pod_creation_failures_total{failure_reason="ImagePullError"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Image pull errors detected
          description: "Image pull errors are occurring at rate {{ $value }} per second"

      - alert: PodCreationInsufficientResources
        expr: rate(pod_creation_failures_total{failure_reason="InsufficientResources"}[5m]) > 0.01
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Insufficient resources for pod creation
          description: "Pod creation failing due to insufficient resources at rate {{ $value }} per second"

      - alert: HighExecutionQueueDepth
        expr: execution_queue_depth > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High execution queue depth
          description: "Execution queue depth is {{ $value }}, which exceeds the threshold of 10"

      - alert: CriticalExecutionQueueDepth
        expr: execution_queue_depth > 20
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: Critical execution queue depth
          description: "Execution queue depth is {{ $value }}, system may be overloaded"

      - alert: HighQueueWaitTime
        expr: histogram_quantile(0.95, rate(execution_queue_wait_time_seconds_bucket[5m])) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High queue wait time
          description: "95th percentile queue wait time is {{ $value }} seconds, above 5 second threshold"

      - alert: CriticalQueueWaitTime
        expr: histogram_quantile(0.95, rate(execution_queue_wait_time_seconds_bucket[5m])) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Critical queue wait time
          description: "95th percentile queue wait time is {{ $value }} seconds, system severely degraded"

      - alert: HighCPUUtilization
        expr: script_cpu_utilization_millicores > 800
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High CPU utilization detected
          description: "Script CPU utilization is {{ $value }} millicores for language {{ $labels.lang_and_version }}"

      - alert: CriticalCPUUtilization
        expr: script_cpu_utilization_millicores > 950
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Critical CPU utilization detected
          description: "Script CPU utilization is {{ $value }} millicores for language {{ $labels.lang_and_version }}, approaching limit"

      - alert: HighMemoryUtilization
        expr: script_memory_utilization_percent > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High memory utilization detected
          description: "Script memory utilization is {{ $value }}% for language {{ $labels.lang_and_version }}"

      - alert: CriticalMemoryUtilization
        expr: script_memory_utilization_percent > 95
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: Critical memory utilization detected
          description: "Script memory utilization is {{ $value }}% for language {{ $labels.lang_and_version }}, risk of OOM"

      - alert: HighSecurityEventRate
        expr: rate(security_events_total[5m]) > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High security event rate detected
          description: "Security events are occurring at rate {{ $value }} per second for event type {{ $labels.event_type }}"

      - alert: NetworkPolicyViolations
        expr: rate(network_policy_violations_total[5m]) > 0.01
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: Network policy violations detected
          description: "Network policy violations detected at rate {{ $value }} per second for policy {{ $labels.policy_name }}"

      - alert: PrivilegeEscalationAttempts
        expr: rate(privilege_escalation_attempts_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: Privilege escalation attempts detected
          description: "Privilege escalation attempts detected for execution {{ $labels.execution_id }}"

      - alert: HighScriptExecutionDuration
        expr: histogram_quantile(0.95, rate(script_execution_duration_seconds_bucket[5m])) > 30
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: High script execution duration
          description: "95th percentile execution time is {{ $value }} seconds for {{ $labels.lang_and_version }}"

      - alert: ScriptExecutionTimeout
        expr: histogram_quantile(0.95, rate(script_execution_duration_seconds_bucket[5m])) > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Script execution approaching timeout
          description: "95th percentile execution time is {{ $value }} seconds for {{ $labels.lang_and_version }}, approaching timeout limit"

      - alert: HighMemoryUsage
        expr: script_memory_usage_mib > 400 * 1024 * 1024
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High script memory usage
          description: "Script memory usage is {{ $value | humanize1024 }}B for {{ $labels.lang_and_version }}"

      # System Health Alerts
      - alert: NoActiveExecutions
        expr: active_executions == 0 and rate(script_executions_total[10m]) == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: No script executions detected
          description: "No script executions have occurred in the last 10 minutes, system may be down"

      - alert: ConsistentPodCreationFailures
        expr: increase(pod_creation_failures_total[10m]) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Consistent pod creation failures
          description: "More than 5 pod creation failures in the last 10 minutes, infrastructure issue likely"