global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'integr8scode'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Only for development
    static_configs:
      - targets: ['app:443']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']