global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'integr8scode'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Only for development
    static_configs:
      - targets: ['app:443']
    metric_relabel_configs:
      - source_labels: [ python_version ]
        regex: '3\.(7|8|9|10|11|12)'
        action: keep
      - source_labels: [ status ]
        regex: '(success|error|timeout|invalid_input|unknown)'
        action: keep

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']