global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'integr8scode'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Only for development
    static_configs:
      - targets: ['backend:443']
    metric_relabel_configs:
      - source_labels: [ lang_and_version ]
        regex: '(.+)-(.+)'
        action: keep
      - source_labels: [ status ]
        regex: '(success|error|timeout|invalid_input|unknown)'
        action: keep

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']