codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flag_management:
  default_rules:
    carryforward: true

  individual_flags:
    - name: backend
      carryforward: true
    - name: frontend
      carryforward: true

component_management:
  individual_components:
    - component_id: backend
      name: Backend
      paths:
        - backend/app/**
    - component_id: frontend
      name: Frontend
      paths:
        - frontend/src/**

ignore:
  - "**/tests/**"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/conftest.py"
