// This file is auto-generated by @hey-api/openapi-ts

export type AdminUserOverview = {
    user: UserResponse;
    stats: EventStatistics;
    derived_counts: DerivedCounts;
    rate_limit_summary: RateLimitSummary;
    recent_events?: Array<{
        [key: string]: unknown;
    }>;
};

export type AlertResponse = {
    message: string;
    alerts_received: number;
    alerts_processed: number;
    errors?: Array<string>;
};

export type BodyLoginApiV1AuthLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

/**
 * Model for cancelling an execution.
 */
export type CancelExecutionRequest = {
    /**
     * Reason for cancellation
     */
    reason?: string | null;
};

/**
 * Model for execution cancellation response.
 */
export type CancelResponse = {
    execution_id: string;
    status: string;
    message: string;
    /**
     * Event ID for the cancellation event, if published
     */
    event_id?: string | null;
};

/**
 * Response schema for cleanup operations
 */
export type CleanupResponse = {
    removed_sessions: number;
    message: string;
};

/**
 * Response model for batch retry operation.
 */
export type DlqBatchRetryResponse = {
    total: number;
    successful: number;
    failed: number;
    details: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Detailed DLQ message response.
 */
export type DlqMessageDetail = {
    event_id: string;
    event: {
        [key: string]: unknown;
    };
    event_type: string;
    original_topic: string;
    error: string;
    retry_count: number;
    failed_at: string;
    status: DlqMessageStatus;
    created_at?: string | null;
    last_updated?: string | null;
    next_retry_at?: string | null;
    retried_at?: string | null;
    discarded_at?: string | null;
    discard_reason?: string | null;
    producer_id: string;
    dlq_offset?: number | null;
    dlq_partition?: number | null;
    last_error?: string | null;
};

/**
 * Response model for a DLQ message.
 */
export type DlqMessageResponse = {
    event_id: string;
    event_type: string;
    original_topic: string;
    error: string;
    retry_count: number;
    failed_at: string;
    status: DlqMessageStatus;
    age_seconds: number;
    details: {
        [key: string]: unknown;
    };
};

/**
 * Status of a message in the Dead Letter Queue.
 */
export type DlqMessageStatus = 'pending' | 'scheduled' | 'retried' | 'discarded';

/**
 * Response model for listing DLQ messages.
 */
export type DlqMessagesResponse = {
    messages: Array<DlqMessageResponse>;
    total: number;
    offset: number;
    limit: number;
};

/**
 * Statistics for the Dead Letter Queue.
 */
export type DlqStats = {
    by_status: {
        [key: string]: number;
    };
    by_topic: Array<{
        [key: string]: unknown;
    }>;
    by_event_type: Array<{
        [key: string]: unknown;
    }>;
    age_stats: {
        [key: string]: unknown;
    };
    timestamp: string;
};

/**
 * Response model for topic summary.
 */
export type DlqTopicSummaryResponse = {
    topic: string;
    total_messages: number;
    status_breakdown: {
        [key: string]: number;
    };
    oldest_message: string;
    newest_message: string;
    avg_retry_count: number;
    max_retry_count: number;
};

/**
 * Response model for deleting events
 */
export type DeleteEventResponse = {
    message: string;
    event_id: string;
    deleted_at: string;
};

/**
 * Response schema for notification deletion
 */
export type DeleteNotificationResponse = {
    message: string;
};

/**
 * Model for execution deletion response.
 */
export type DeleteResponse = {
    message: string;
    execution_id: string;
};

export type DerivedCounts = {
    succeeded?: number;
    failed?: number;
    timeout?: number;
    cancelled?: number;
    terminal_total?: number;
};

/**
 * Code editor preferences
 */
export type EditorSettings = {
    theme?: string;
    font_size?: number;
    tab_size?: number;
    use_tabs?: boolean;
    word_wrap?: boolean;
    show_line_numbers?: boolean;
    font_family?: string;
    auto_complete?: boolean;
    bracket_matching?: boolean;
    highlight_active_line?: boolean;
    default_language?: string;
};

export type EndpointGroup = 'execution' | 'admin' | 'sse' | 'websocket' | 'auth' | 'public' | 'api';

/**
 * Classification of error types in execution platform.
 */
export type ErrorType = 'script_error' | 'system_error' | 'success';

/**
 * Request model for event aggregation queries.
 */
export type EventAggregationRequest = {
    /**
     * MongoDB aggregation pipeline
     */
    pipeline: Array<{
        [key: string]: unknown;
    }>;
    limit?: number;
};

/**
 * Request model for browsing events
 */
export type EventBrowseRequest = {
    filters: EventFilter;
    skip?: number;
    limit?: number;
    sort_by?: string;
    sort_order?: number;
};

/**
 * Response model for browsing events
 */
export type EventBrowseResponse = {
    events: Array<{
        [key: string]: unknown;
    }>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * Response model for event deletion
 */
export type EventDeleteResponse = {
    message: string;
    event_id: string;
};

/**
 * Response model for event detail
 */
export type EventDetailResponse = {
    event: {
        [key: string]: unknown;
    };
    related_events: Array<{
        [key: string]: unknown;
    }>;
    timeline: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Filter criteria for browsing events
 */
export type EventFilter = {
    event_types?: Array<EventType> | null;
    aggregate_id?: string | null;
    correlation_id?: string | null;
    user_id?: string | null;
    start_time?: string | null;
    end_time?: string | null;
    service_name?: string | null;
    search_text?: string | null;
};

/**
 * Request model for filtering events.
 */
export type EventFilterRequest = {
    /**
     * Filter by event types
     */
    event_types?: Array<EventType> | null;
    /**
     * Filter by aggregate ID
     */
    aggregate_id?: string | null;
    /**
     * Filter by correlation ID
     */
    correlation_id?: string | null;
    /**
     * Filter by user ID (admin only)
     */
    user_id?: string | null;
    /**
     * Filter by service name
     */
    service_name?: string | null;
    /**
     * Filter events after this time
     */
    start_time?: string | null;
    /**
     * Filter events before this time
     */
    end_time?: string | null;
    /**
     * Full-text search in event data
     */
    text_search?: string | null;
    /**
     * Field to sort by
     */
    sort_by?: string;
    /**
     * Sort order
     */
    sort_order?: SortOrder;
    /**
     * Maximum events to return
     */
    limit?: number;
    /**
     * Number of events to skip
     */
    skip?: number;
};

export type EventListResponse = {
    events: Array<EventResponse>;
    total: number;
    limit: number;
    skip: number;
    has_more: boolean;
};

/**
 * Request model for replaying events
 */
export type EventReplayRequest = {
    event_ids?: Array<string> | null;
    correlation_id?: string | null;
    aggregate_id?: string | null;
    start_time?: string | null;
    end_time?: string | null;
    target_service?: string | null;
    dry_run?: boolean;
};

/**
 * Response model for event replay
 */
export type EventReplayResponse = {
    dry_run: boolean;
    total_events: number;
    replay_correlation_id: string;
    session_id?: string | null;
    status: string;
    events_preview?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * Response model for replay status
 */
export type EventReplayStatusResponse = {
    session_id: string;
    status: string;
    total_events: number;
    replayed_events: number;
    failed_events: number;
    skipped_events: number;
    correlation_id: string;
    created_at: string;
    started_at?: string | null;
    completed_at?: string | null;
    error?: string | null;
    progress_percentage: number;
    estimated_completion?: string | null;
    execution_results?: Array<{
        [key: string]: unknown;
    }> | null;
};

export type EventResponse = {
    event_id: string;
    event_type: EventType;
    event_version: string;
    timestamp: string;
    aggregate_id?: string | null;
    correlation_id?: string | null;
    causation_id?: string | null;
    metadata: {
        [key: string]: unknown;
    };
    payload: {
        [key: string]: unknown;
    };
    stored_at?: string | null;
};

/**
 * Event statistics response.
 */
export type EventStatistics = {
    total_events: number;
    events_by_type: {
        [key: string]: number;
    };
    events_by_service: {
        [key: string]: number;
    };
    events_by_hour: Array<{
        [key: string]: unknown;
    }>;
    start_time?: string | null;
    end_time?: string | null;
};

/**
 * Response model for event statistics
 */
export type EventStatsResponse = {
    total_events: number;
    events_by_type: {
        [key: string]: number;
    };
    events_by_hour: Array<{
        [key: string]: unknown;
    }>;
    top_users: Array<{
        [key: string]: unknown;
    }>;
    error_rate: number;
    avg_processing_time: number;
};

/**
 * Event types used throughout the system.
 */
export type EventType = 'execution_requested' | 'execution_accepted' | 'execution_queued' | 'execution_started' | 'execution_running' | 'execution_completed' | 'execution_failed' | 'execution_timeout' | 'execution_cancelled' | 'pod_created' | 'pod_scheduled' | 'pod_running' | 'pod_succeeded' | 'pod_failed' | 'pod_terminated' | 'pod_deleted' | 'user_registered' | 'user_login' | 'user_logged_in' | 'user_logged_out' | 'user_updated' | 'user_deleted' | 'user_settings_updated' | 'user_theme_changed' | 'user_notification_settings_updated' | 'user_editor_settings_updated' | 'notification_created' | 'notification_sent' | 'notification_delivered' | 'notification_failed' | 'notification_read' | 'notification_clicked' | 'notification_preferences_updated' | 'script_saved' | 'script_deleted' | 'script_shared' | 'security_violation' | 'rate_limit_exceeded' | 'auth_failed' | 'resource_limit_exceeded' | 'quota_exceeded' | 'system_error' | 'service_unhealthy' | 'service_recovered' | 'result_stored' | 'result_failed' | 'saga_started' | 'saga_completed' | 'saga_failed' | 'saga_cancelled' | 'saga_compensating' | 'saga_compensated' | 'create_pod_command' | 'delete_pod_command' | 'allocate_resources_command' | 'release_resources_command';

/**
 * Model for example scripts.
 */
export type ExampleScripts = {
    scripts: {
        [key: string]: string;
    };
};

/**
 * Model for execution event response.
 */
export type ExecutionEventResponse = {
    event_id: string;
    event_type: string;
    timestamp: string;
    payload: {
        [key: string]: unknown;
    };
};

/**
 * Execution resource limits schema.
 */
export type ExecutionLimitsSchema = {
    /**
     * Maximum execution timeout
     */
    max_timeout_seconds?: number;
    /**
     * Maximum memory in MB
     */
    max_memory_mb?: number;
    /**
     * Maximum CPU cores
     */
    max_cpu_cores?: number;
    /**
     * Maximum concurrent executions
     */
    max_concurrent_executions?: number;
};

/**
 * Model for paginated execution list.
 */
export type ExecutionListResponse = {
    executions: Array<ExecutionResult>;
    total: number;
    limit: number;
    skip: number;
    has_more: boolean;
};

/**
 * Model for execution request.
 */
export type ExecutionRequest = {
    /**
     * Script content (max 50,000 characters)
     */
    script: string;
    /**
     * Language name
     */
    lang?: string;
    /**
     * Language version to use for execution
     */
    lang_version?: string;
};

/**
 * Model for execution response.
 */
export type ExecutionResponse = {
    execution_id: string;
    status: ExecutionStatus;
};

/**
 * Model for execution result.
 */
export type ExecutionResult = {
    execution_id: string;
    status: ExecutionStatus;
    stdout?: string | null;
    stderr?: string | null;
    lang: string;
    lang_version: string;
    resource_usage?: ResourceUsage | null;
    exit_code?: number | null;
    error_type?: ErrorType | null;
};

/**
 * Status of an execution.
 */
export type ExecutionStatus = 'queued' | 'scheduled' | 'running' | 'completed' | 'failed' | 'timeout' | 'cancelled' | 'error';

export type GrafanaAlertItem = {
    status?: string | null;
    labels?: {
        [key: string]: string;
    };
    annotations?: {
        [key: string]: string;
    };
    valueString?: string | null;
};

export type GrafanaWebhook = {
    status?: string | null;
    receiver?: string | null;
    alerts?: Array<GrafanaAlertItem>;
    groupLabels?: {
        [key: string]: string;
    };
    commonLabels?: {
        [key: string]: string;
    };
    commonAnnotations?: {
        [key: string]: string;
    };
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response model for successful login
 */
export type LoginResponse = {
    message: string;
    username: string;
    role: string;
    csrf_token: string;
};

/**
 * Request model for manual retry of messages.
 */
export type ManualRetryRequest = {
    event_ids: Array<string>;
};

/**
 * Generic message response
 */
export type MessageResponse = {
    message: string;
};

/**
 * Monitoring and observability schema.
 */
export type MonitoringSettingsSchema = {
    /**
     * Metrics retention in days
     */
    metrics_retention_days?: number;
    /**
     * Log level
     */
    log_level?: string;
    /**
     * Enable distributed tracing
     */
    enable_tracing?: boolean;
    /**
     * Trace sampling rate
     */
    sampling_rate?: number;
};

/**
 * Notification delivery channels.
 */
export type NotificationChannel = 'in_app' | 'webhook' | 'slack';

/**
 * Response schema for notification list endpoints
 */
export type NotificationListResponse = {
    notifications: Array<NotificationResponse>;
    total: number;
    unread_count: number;
};

/**
 * Response schema for notification endpoints
 */
export type NotificationResponse = {
    notification_id: string;
    channel: NotificationChannel;
    status: NotificationStatus;
    subject: string;
    body: string;
    action_url: string | null;
    created_at: string;
    read_at: string | null;
    severity: NotificationSeverity;
    tags: Array<string>;
};

/**
 * User notification preferences
 */
export type NotificationSettings = {
    execution_completed?: boolean;
    execution_failed?: boolean;
    system_updates?: boolean;
    security_alerts?: boolean;
    channels?: Array<NotificationChannel>;
};

/**
 * Notification severity levels.
 */
export type NotificationSeverity = 'low' | 'medium' | 'high' | 'urgent';

/**
 * Notification delivery status.
 */
export type NotificationStatus = 'pending' | 'queued' | 'sending' | 'delivered' | 'failed' | 'skipped' | 'read' | 'clicked';

/**
 * User subscription preferences for notifications
 */
export type NotificationSubscription = {
    user_id: string;
    channel: NotificationChannel;
    severities?: Array<NotificationSeverity>;
    include_tags?: Array<string>;
    exclude_tags?: Array<string>;
    enabled?: boolean;
    webhook_url?: string | null;
    slack_webhook?: string | null;
    quiet_hours_enabled?: boolean;
    quiet_hours_start?: string | null;
    quiet_hours_end?: string | null;
    timezone?: string;
    batch_interval_minutes?: number;
    created_at?: string;
    updated_at?: string;
};

/**
 * Request model for password reset
 */
export type PasswordResetRequest = {
    /**
     * New password for the user
     */
    new_password: string;
};

/**
 * Request model for publishing events.
 */
export type PublishEventRequest = {
    /**
     * Type of event to publish
     */
    event_type: EventType;
    /**
     * Event payload data
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Aggregate root ID
     */
    aggregate_id?: string | null;
    /**
     * Correlation ID
     */
    correlation_id?: string | null;
    /**
     * ID of causing event
     */
    causation_id?: string | null;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Response model for publishing events
 */
export type PublishEventResponse = {
    event_id: string;
    status: string;
    timestamp: string;
};

export type RateLimitAlgorithm = 'sliding_window' | 'token_bucket' | 'fixed_window' | 'leaky_bucket';

export type RateLimitRule = {
    endpoint_pattern: string;
    group: EndpointGroup;
    requests: number;
    window_seconds: number;
    burst_multiplier?: number;
    algorithm?: RateLimitAlgorithm;
    priority?: number;
    enabled?: boolean;
    compiled_pattern?: string | null;
};

export type RateLimitSummary = {
    bypass_rate_limit?: boolean | null;
    global_multiplier?: number | null;
    has_custom_limits?: boolean | null;
};

/**
 * Response model for replaying aggregate events
 */
export type ReplayAggregateResponse = {
    dry_run: boolean;
    aggregate_id: string;
    event_count?: number | null;
    event_types?: Array<string> | null;
    start_time?: string | null;
    end_time?: string | null;
    replayed_count?: number | null;
    replay_correlation_id?: string | null;
};

export type ReplayConfigSchema = {
    replay_type: ReplayType;
    target?: ReplayTarget;
    filter: ReplayFilterSchema;
    speed_multiplier?: number;
    preserve_timestamps?: boolean;
    batch_size?: number;
    max_events?: number | null;
    target_topics?: {
        [key: string]: string;
    } | null;
    target_file_path?: string | null;
    skip_errors?: boolean;
    retry_failed?: boolean;
    retry_attempts?: number;
    enable_progress_tracking?: boolean;
};

export type ReplayFilterSchema = {
    execution_id?: string | null;
    event_types?: Array<string> | null;
    start_time?: string | null;
    end_time?: string | null;
    user_id?: string | null;
    service_name?: string | null;
    custom_query?: {
        [key: string]: unknown;
    } | null;
    exclude_event_types?: Array<string> | null;
};

/**
 * Request schema for creating replay sessions
 */
export type ReplayRequest = {
    replay_type: ReplayType;
    target?: ReplayTarget;
    execution_id?: string | null;
    event_types?: Array<EventType> | null;
    start_time?: string | null;
    end_time?: string | null;
    user_id?: string | null;
    service_name?: string | null;
    speed_multiplier?: number;
    preserve_timestamps?: boolean;
    batch_size?: number;
    max_events?: number | null;
    skip_errors?: boolean;
    target_file_path?: string | null;
};

/**
 * Response schema for replay operations
 */
export type ReplayResponse = {
    session_id: string;
    status: ReplayStatus;
    message: string;
};

export type ReplaySession = {
    session_id?: string;
    config: ReplayConfigSchema;
    status?: ReplayStatus;
    total_events?: number;
    replayed_events?: number;
    failed_events?: number;
    skipped_events?: number;
    created_at?: string;
    started_at?: string | null;
    completed_at?: string | null;
    last_event_at?: string | null;
    errors?: Array<{
        [key: string]: unknown;
    }>;
};

export type ReplayStatus = 'scheduled' | 'created' | 'running' | 'paused' | 'completed' | 'failed' | 'cancelled';

export type ReplayTarget = 'kafka' | 'callback' | 'file' | 'test';

export type ReplayType = 'execution' | 'time_range' | 'event_type' | 'query' | 'recovery';

/**
 * Model for resource limits configuration.
 */
export type ResourceLimits = {
    cpu_limit: string;
    memory_limit: string;
    cpu_request: string;
    memory_request: string;
    execution_timeout: number;
    supported_runtimes: {
        [key: string]: Array<string>;
    };
};

/**
 * Model for execution resource usage.
 */
export type ResourceUsage = {
    /**
     * Wall clock execution time in seconds
     */
    execution_time_wall_seconds?: number | null;
    /**
     * CPU time in jiffies (multiply by 10 for milliseconds)
     */
    cpu_time_jiffies?: number | null;
    /**
     * Clock ticks per second (usually 100)
     */
    clk_tck_hertz?: number | null;
    /**
     * Peak memory usage in KB
     */
    peak_memory_kb?: number | null;
};

/**
 * Request model for restoring settings
 */
export type RestoreSettingsRequest = {
    timestamp: string;
    reason?: string | null;
};

/**
 * Model for retrying an execution.
 */
export type RetryExecutionRequest = {
    /**
     * Reason for retry
     */
    reason?: string | null;
    /**
     * Keep output from previous attempt
     */
    preserve_output?: boolean;
};

/**
 * Request model for setting a retry policy.
 */
export type RetryPolicyRequest = {
    topic: string;
    strategy: RetryStrategy;
    max_retries?: number;
    base_delay_seconds?: number;
    max_delay_seconds?: number;
    retry_multiplier?: number;
};

/**
 * Retry strategies for DLQ messages.
 */
export type RetryStrategy = 'immediate' | 'exponential_backoff' | 'fixed_interval' | 'scheduled' | 'manual';

/**
 * Response model for SSE health check.
 */
export type SseHealthResponse = {
    /**
     * Health status: healthy or draining
     */
    status: string;
    /**
     * Whether Kafka features are enabled
     */
    kafka_enabled?: boolean;
    /**
     * Total number of active SSE connections
     */
    active_connections: number;
    /**
     * Number of executions being monitored
     */
    active_executions: number;
    /**
     * Number of active Kafka consumers
     */
    active_consumers: number;
    /**
     * Maximum connections allowed per user
     */
    max_connections_per_user: number;
    /**
     * Shutdown status information
     */
    shutdown: {
        [key: string]: unknown;
    };
    /**
     * Health check timestamp
     */
    timestamp: string;
};

/**
 * Response schema for saga cancellation
 */
export type SagaCancellationResponse = {
    success: boolean;
    message: string;
    saga_id: string;
};

/**
 * Response schema for saga list
 */
export type SagaListResponse = {
    sagas: Array<SagaStatusResponse>;
    total: number;
};

/**
 * Saga execution states.
 */
export type SagaState = 'created' | 'running' | 'compensating' | 'completed' | 'failed' | 'timeout' | 'cancelled';

/**
 * Response schema for saga status
 */
export type SagaStatusResponse = {
    saga_id: string;
    saga_name: string;
    execution_id: string;
    state: SagaState;
    current_step: string | null;
    completed_steps: Array<string>;
    compensated_steps: Array<string>;
    error_message: string | null;
    created_at: string;
    updated_at: string;
    completed_at: string | null;
    retry_count: number;
};

export type SavedScriptCreateRequest = {
    name: string;
    script: string;
    lang?: string;
    lang_version?: string;
    description?: string | null;
};

export type SavedScriptResponse = {
    script_id: string;
    name: string;
    script: string;
    lang: string;
    lang_version: string;
    description?: string | null;
    created_at: string;
    updated_at: string;
};

/**
 * Security configuration schema.
 */
export type SecuritySettingsSchema = {
    /**
     * Minimum password length
     */
    password_min_length?: number;
    /**
     * Session timeout in minutes
     */
    session_timeout_minutes?: number;
    /**
     * Maximum login attempts
     */
    max_login_attempts?: number;
    /**
     * Account lockout duration
     */
    lockout_duration_minutes?: number;
};

/**
 * Summary information for replay sessions
 */
export type SessionSummary = {
    session_id: string;
    replay_type: ReplayType;
    target: ReplayTarget;
    status: ReplayStatus;
    total_events: number;
    replayed_events: number;
    failed_events: number;
    skipped_events: number;
    created_at: string;
    started_at: string | null;
    completed_at: string | null;
    duration_seconds?: number | null;
    throughput_events_per_second?: number | null;
};

/**
 * Single entry in settings history
 */
export type SettingsHistoryEntry = {
    timestamp: string;
    event_type: string;
    field: string;
    old_value: unknown;
    new_value: unknown;
    reason?: string | null;
    correlation_id?: string | null;
};

/**
 * Response model for settings history
 */
export type SettingsHistoryResponse = {
    history: Array<SettingsHistoryEntry>;
    total: number;
};

/**
 * Sort order for queries.
 */
export type SortOrder = 'asc' | 'desc';

/**
 * Request schema for updating notification subscriptions
 */
export type SubscriptionUpdate = {
    enabled: boolean;
    severities?: Array<NotificationSeverity>;
    include_tags?: Array<string>;
    exclude_tags?: Array<string>;
    webhook_url?: string | null;
    slack_webhook?: string | null;
    quiet_hours_enabled?: boolean;
    quiet_hours_start?: string | null;
    quiet_hours_end?: string | null;
    timezone?: string;
    batch_interval_minutes?: number;
};

/**
 * Response schema for user subscriptions
 */
export type SubscriptionsResponse = {
    subscriptions: Array<NotificationSubscription>;
};

/**
 * System-wide settings model.
 */
export type SystemSettings = {
    execution_limits?: ExecutionLimitsSchema;
    security_settings?: SecuritySettingsSchema;
    monitoring_settings?: MonitoringSettingsSchema;
};

/**
 * Available UI themes.
 */
export type Theme = 'light' | 'dark' | 'auto';

/**
 * Request model for theme update
 */
export type ThemeUpdateRequest = {
    theme: Theme;
};

/**
 * Response model for token validation
 */
export type TokenValidationResponse = {
    valid: boolean;
    username: string;
    role: string;
    csrf_token: string;
};

/**
 * Response schema for unread notification count
 */
export type UnreadCountResponse = {
    unread_count: number;
};

/**
 * Model for creating a new user
 */
export type UserCreate = {
    username: string;
    email: string;
    role?: UserRole;
    is_active?: boolean;
    password: string;
};

/**
 * Response model for listing users
 */
export type UserListResponse = {
    users: Array<UserResponse>;
    total: number;
    offset: number;
    limit: number;
};

export type UserRateLimit = {
    user_id: string;
    rules?: Array<RateLimitRule>;
    global_multiplier?: number;
    bypass_rate_limit?: boolean;
    created_at?: string;
    updated_at?: string;
    notes?: string | null;
};

/**
 * User model for API responses (without password)
 */
export type UserResponse = {
    username: string;
    email: string;
    role?: UserRole;
    is_active?: boolean;
    user_id: string;
    is_superuser?: boolean;
    created_at: string;
    updated_at: string;
    bypass_rate_limit?: boolean | null;
    global_multiplier?: number | null;
    has_custom_limits?: boolean | null;
};

/**
 * User roles in the system.
 */
export type UserRole = 'user' | 'admin' | 'moderator';

/**
 * Complete user settings model
 */
export type UserSettings = {
    user_id: string;
    theme?: Theme;
    timezone?: string;
    date_format?: string;
    time_format?: string;
    notifications?: NotificationSettings;
    editor?: EditorSettings;
    custom_settings?: {
        [key: string]: unknown;
    };
    version?: number;
    created_at?: string;
    updated_at?: string;
};

/**
 * Partial update model for user settings
 */
export type UserSettingsUpdate = {
    theme?: Theme | null;
    timezone?: string | null;
    date_format?: string | null;
    time_format?: string | null;
    notifications?: NotificationSettings | null;
    editor?: EditorSettings | null;
    custom_settings?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Model for updating a user
 */
export type UserUpdate = {
    username?: string | null;
    email?: string | null;
    role?: UserRole | null;
    is_active?: boolean | null;
    password?: string | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type GetCurrentUserProfileApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserProfileApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserProfileApiV1AuthMeGetResponse = GetCurrentUserProfileApiV1AuthMeGetResponses[keyof GetCurrentUserProfileApiV1AuthMeGetResponses];

export type VerifyTokenApiV1AuthVerifyTokenGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-token';
};

export type VerifyTokenApiV1AuthVerifyTokenGetResponses = {
    /**
     * Successful Response
     */
    200: TokenValidationResponse;
};

export type VerifyTokenApiV1AuthVerifyTokenGetResponse = VerifyTokenApiV1AuthVerifyTokenGetResponses[keyof VerifyTokenApiV1AuthVerifyTokenGetResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type CreateExecutionApiV1ExecutePostData = {
    body: ExecutionRequest;
    headers?: {
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/execute';
};

export type CreateExecutionApiV1ExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExecutionApiV1ExecutePostError = CreateExecutionApiV1ExecutePostErrors[keyof CreateExecutionApiV1ExecutePostErrors];

export type CreateExecutionApiV1ExecutePostResponses = {
    /**
     * Successful Response
     */
    200: ExecutionResponse;
};

export type CreateExecutionApiV1ExecutePostResponse = CreateExecutionApiV1ExecutePostResponses[keyof CreateExecutionApiV1ExecutePostResponses];

export type GetResultApiV1ResultExecutionIdGetData = {
    body?: never;
    path: {
        execution_id: string;
    };
    query?: never;
    url: '/api/v1/result/{execution_id}';
};

export type GetResultApiV1ResultExecutionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResultApiV1ResultExecutionIdGetError = GetResultApiV1ResultExecutionIdGetErrors[keyof GetResultApiV1ResultExecutionIdGetErrors];

export type GetResultApiV1ResultExecutionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ExecutionResult;
};

export type GetResultApiV1ResultExecutionIdGetResponse = GetResultApiV1ResultExecutionIdGetResponses[keyof GetResultApiV1ResultExecutionIdGetResponses];

export type CancelExecutionApiV1ExecutionIdCancelPostData = {
    body: CancelExecutionRequest;
    path: {
        execution_id: string;
    };
    query?: never;
    url: '/api/v1/{execution_id}/cancel';
};

export type CancelExecutionApiV1ExecutionIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelExecutionApiV1ExecutionIdCancelPostError = CancelExecutionApiV1ExecutionIdCancelPostErrors[keyof CancelExecutionApiV1ExecutionIdCancelPostErrors];

export type CancelExecutionApiV1ExecutionIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: CancelResponse;
};

export type CancelExecutionApiV1ExecutionIdCancelPostResponse = CancelExecutionApiV1ExecutionIdCancelPostResponses[keyof CancelExecutionApiV1ExecutionIdCancelPostResponses];

export type RetryExecutionApiV1ExecutionIdRetryPostData = {
    body: RetryExecutionRequest;
    path: {
        execution_id: string;
    };
    query?: never;
    url: '/api/v1/{execution_id}/retry';
};

export type RetryExecutionApiV1ExecutionIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryExecutionApiV1ExecutionIdRetryPostError = RetryExecutionApiV1ExecutionIdRetryPostErrors[keyof RetryExecutionApiV1ExecutionIdRetryPostErrors];

export type RetryExecutionApiV1ExecutionIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: ExecutionResponse;
};

export type RetryExecutionApiV1ExecutionIdRetryPostResponse = RetryExecutionApiV1ExecutionIdRetryPostResponses[keyof RetryExecutionApiV1ExecutionIdRetryPostResponses];

export type GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetData = {
    body?: never;
    path: {
        execution_id: string;
    };
    query?: {
        /**
         * Comma-separated event types to filter
         */
        event_types?: string | null;
        limit?: number;
    };
    url: '/api/v1/executions/{execution_id}/events';
};

export type GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetError = GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetErrors[keyof GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetErrors];

export type GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ExecutionEventResponse>;
};

export type GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetResponse = GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetResponses[keyof GetExecutionEventsApiV1ExecutionsExecutionIdEventsGetResponses];

export type GetUserExecutionsApiV1UserExecutionsGetData = {
    body?: never;
    path?: never;
    query?: {
        status?: ExecutionStatus | null;
        lang?: string | null;
        start_time?: string | null;
        end_time?: string | null;
        limit?: number;
        skip?: number;
    };
    url: '/api/v1/user/executions';
};

export type GetUserExecutionsApiV1UserExecutionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserExecutionsApiV1UserExecutionsGetError = GetUserExecutionsApiV1UserExecutionsGetErrors[keyof GetUserExecutionsApiV1UserExecutionsGetErrors];

export type GetUserExecutionsApiV1UserExecutionsGetResponses = {
    /**
     * Successful Response
     */
    200: ExecutionListResponse;
};

export type GetUserExecutionsApiV1UserExecutionsGetResponse = GetUserExecutionsApiV1UserExecutionsGetResponses[keyof GetUserExecutionsApiV1UserExecutionsGetResponses];

export type GetExampleScriptsApiV1ExampleScriptsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/example-scripts';
};

export type GetExampleScriptsApiV1ExampleScriptsGetResponses = {
    /**
     * Successful Response
     */
    200: ExampleScripts;
};

export type GetExampleScriptsApiV1ExampleScriptsGetResponse = GetExampleScriptsApiV1ExampleScriptsGetResponses[keyof GetExampleScriptsApiV1ExampleScriptsGetResponses];

export type GetK8sResourceLimitsApiV1K8sLimitsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/k8s-limits';
};

export type GetK8sResourceLimitsApiV1K8sLimitsGetResponses = {
    /**
     * Successful Response
     */
    200: ResourceLimits;
};

export type GetK8sResourceLimitsApiV1K8sLimitsGetResponse = GetK8sResourceLimitsApiV1K8sLimitsGetResponses[keyof GetK8sResourceLimitsApiV1K8sLimitsGetResponses];

export type DeleteExecutionApiV1ExecutionIdDeleteData = {
    body?: never;
    path: {
        execution_id: string;
    };
    query?: never;
    url: '/api/v1/{execution_id}';
};

export type DeleteExecutionApiV1ExecutionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExecutionApiV1ExecutionIdDeleteError = DeleteExecutionApiV1ExecutionIdDeleteErrors[keyof DeleteExecutionApiV1ExecutionIdDeleteErrors];

export type DeleteExecutionApiV1ExecutionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteExecutionApiV1ExecutionIdDeleteResponse = DeleteExecutionApiV1ExecutionIdDeleteResponses[keyof DeleteExecutionApiV1ExecutionIdDeleteResponses];

export type ListSavedScriptsApiV1ScriptsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scripts';
};

export type ListSavedScriptsApiV1ScriptsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<SavedScriptResponse>;
};

export type ListSavedScriptsApiV1ScriptsGetResponse = ListSavedScriptsApiV1ScriptsGetResponses[keyof ListSavedScriptsApiV1ScriptsGetResponses];

export type CreateSavedScriptApiV1ScriptsPostData = {
    body: SavedScriptCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/scripts';
};

export type CreateSavedScriptApiV1ScriptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSavedScriptApiV1ScriptsPostError = CreateSavedScriptApiV1ScriptsPostErrors[keyof CreateSavedScriptApiV1ScriptsPostErrors];

export type CreateSavedScriptApiV1ScriptsPostResponses = {
    /**
     * Successful Response
     */
    200: SavedScriptResponse;
};

export type CreateSavedScriptApiV1ScriptsPostResponse = CreateSavedScriptApiV1ScriptsPostResponses[keyof CreateSavedScriptApiV1ScriptsPostResponses];

export type DeleteSavedScriptApiV1ScriptsScriptIdDeleteData = {
    body?: never;
    path: {
        script_id: string;
    };
    query?: never;
    url: '/api/v1/scripts/{script_id}';
};

export type DeleteSavedScriptApiV1ScriptsScriptIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSavedScriptApiV1ScriptsScriptIdDeleteError = DeleteSavedScriptApiV1ScriptsScriptIdDeleteErrors[keyof DeleteSavedScriptApiV1ScriptsScriptIdDeleteErrors];

export type DeleteSavedScriptApiV1ScriptsScriptIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSavedScriptApiV1ScriptsScriptIdDeleteResponse = DeleteSavedScriptApiV1ScriptsScriptIdDeleteResponses[keyof DeleteSavedScriptApiV1ScriptsScriptIdDeleteResponses];

export type GetSavedScriptApiV1ScriptsScriptIdGetData = {
    body?: never;
    path: {
        script_id: string;
    };
    query?: never;
    url: '/api/v1/scripts/{script_id}';
};

export type GetSavedScriptApiV1ScriptsScriptIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSavedScriptApiV1ScriptsScriptIdGetError = GetSavedScriptApiV1ScriptsScriptIdGetErrors[keyof GetSavedScriptApiV1ScriptsScriptIdGetErrors];

export type GetSavedScriptApiV1ScriptsScriptIdGetResponses = {
    /**
     * Successful Response
     */
    200: SavedScriptResponse;
};

export type GetSavedScriptApiV1ScriptsScriptIdGetResponse = GetSavedScriptApiV1ScriptsScriptIdGetResponses[keyof GetSavedScriptApiV1ScriptsScriptIdGetResponses];

export type UpdateSavedScriptApiV1ScriptsScriptIdPutData = {
    body: SavedScriptCreateRequest;
    path: {
        script_id: string;
    };
    query?: never;
    url: '/api/v1/scripts/{script_id}';
};

export type UpdateSavedScriptApiV1ScriptsScriptIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSavedScriptApiV1ScriptsScriptIdPutError = UpdateSavedScriptApiV1ScriptsScriptIdPutErrors[keyof UpdateSavedScriptApiV1ScriptsScriptIdPutErrors];

export type UpdateSavedScriptApiV1ScriptsScriptIdPutResponses = {
    /**
     * Successful Response
     */
    200: SavedScriptResponse;
};

export type UpdateSavedScriptApiV1ScriptsScriptIdPutResponse = UpdateSavedScriptApiV1ScriptsScriptIdPutResponses[keyof UpdateSavedScriptApiV1ScriptsScriptIdPutResponses];

export type ListReplaySessionsApiV1ReplaySessionsGetData = {
    body?: never;
    path?: never;
    query?: {
        status?: ReplayStatus | null;
        limit?: number;
    };
    url: '/api/v1/replay/sessions';
};

export type ListReplaySessionsApiV1ReplaySessionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListReplaySessionsApiV1ReplaySessionsGetError = ListReplaySessionsApiV1ReplaySessionsGetErrors[keyof ListReplaySessionsApiV1ReplaySessionsGetErrors];

export type ListReplaySessionsApiV1ReplaySessionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<SessionSummary>;
};

export type ListReplaySessionsApiV1ReplaySessionsGetResponse = ListReplaySessionsApiV1ReplaySessionsGetResponses[keyof ListReplaySessionsApiV1ReplaySessionsGetResponses];

export type CreateReplaySessionApiV1ReplaySessionsPostData = {
    body: ReplayRequest;
    path?: never;
    query?: never;
    url: '/api/v1/replay/sessions';
};

export type CreateReplaySessionApiV1ReplaySessionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReplaySessionApiV1ReplaySessionsPostError = CreateReplaySessionApiV1ReplaySessionsPostErrors[keyof CreateReplaySessionApiV1ReplaySessionsPostErrors];

export type CreateReplaySessionApiV1ReplaySessionsPostResponses = {
    /**
     * Successful Response
     */
    200: ReplayResponse;
};

export type CreateReplaySessionApiV1ReplaySessionsPostResponse = CreateReplaySessionApiV1ReplaySessionsPostResponses[keyof CreateReplaySessionApiV1ReplaySessionsPostResponses];

export type StartReplaySessionApiV1ReplaySessionsSessionIdStartPostData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/replay/sessions/{session_id}/start';
};

export type StartReplaySessionApiV1ReplaySessionsSessionIdStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartReplaySessionApiV1ReplaySessionsSessionIdStartPostError = StartReplaySessionApiV1ReplaySessionsSessionIdStartPostErrors[keyof StartReplaySessionApiV1ReplaySessionsSessionIdStartPostErrors];

export type StartReplaySessionApiV1ReplaySessionsSessionIdStartPostResponses = {
    /**
     * Successful Response
     */
    200: ReplayResponse;
};

export type StartReplaySessionApiV1ReplaySessionsSessionIdStartPostResponse = StartReplaySessionApiV1ReplaySessionsSessionIdStartPostResponses[keyof StartReplaySessionApiV1ReplaySessionsSessionIdStartPostResponses];

export type PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/replay/sessions/{session_id}/pause';
};

export type PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostError = PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostErrors[keyof PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostErrors];

export type PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostResponses = {
    /**
     * Successful Response
     */
    200: ReplayResponse;
};

export type PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostResponse = PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostResponses[keyof PauseReplaySessionApiV1ReplaySessionsSessionIdPausePostResponses];

export type ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/replay/sessions/{session_id}/resume';
};

export type ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostError = ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostErrors[keyof ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostErrors];

export type ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: ReplayResponse;
};

export type ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostResponse = ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostResponses[keyof ResumeReplaySessionApiV1ReplaySessionsSessionIdResumePostResponses];

export type CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/replay/sessions/{session_id}/cancel';
};

export type CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostError = CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostErrors[keyof CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostErrors];

export type CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: ReplayResponse;
};

export type CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostResponse = CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostResponses[keyof CancelReplaySessionApiV1ReplaySessionsSessionIdCancelPostResponses];

export type GetReplaySessionApiV1ReplaySessionsSessionIdGetData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/replay/sessions/{session_id}';
};

export type GetReplaySessionApiV1ReplaySessionsSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReplaySessionApiV1ReplaySessionsSessionIdGetError = GetReplaySessionApiV1ReplaySessionsSessionIdGetErrors[keyof GetReplaySessionApiV1ReplaySessionsSessionIdGetErrors];

export type GetReplaySessionApiV1ReplaySessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReplaySession;
};

export type GetReplaySessionApiV1ReplaySessionsSessionIdGetResponse = GetReplaySessionApiV1ReplaySessionsSessionIdGetResponses[keyof GetReplaySessionApiV1ReplaySessionsSessionIdGetResponses];

export type CleanupOldSessionsApiV1ReplayCleanupPostData = {
    body?: never;
    path?: never;
    query?: {
        older_than_hours?: number;
    };
    url: '/api/v1/replay/cleanup';
};

export type CleanupOldSessionsApiV1ReplayCleanupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CleanupOldSessionsApiV1ReplayCleanupPostError = CleanupOldSessionsApiV1ReplayCleanupPostErrors[keyof CleanupOldSessionsApiV1ReplayCleanupPostErrors];

export type CleanupOldSessionsApiV1ReplayCleanupPostResponses = {
    /**
     * Successful Response
     */
    200: CleanupResponse;
};

export type CleanupOldSessionsApiV1ReplayCleanupPostResponse = CleanupOldSessionsApiV1ReplayCleanupPostResponses[keyof CleanupOldSessionsApiV1ReplayCleanupPostResponses];

export type LivenessApiV1HealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type LivenessApiV1HealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type LivenessApiV1HealthLiveGetResponse = LivenessApiV1HealthLiveGetResponses[keyof LivenessApiV1HealthLiveGetResponses];

export type ReadinessApiV1HealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type ReadinessApiV1HealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReadinessApiV1HealthReadyGetResponse = ReadinessApiV1HealthReadyGetResponses[keyof ReadinessApiV1HealthReadyGetResponses];

export type GetDlqStatisticsApiV1DlqStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dlq/stats';
};

export type GetDlqStatisticsApiV1DlqStatsGetResponses = {
    /**
     * Successful Response
     */
    200: DlqStats;
};

export type GetDlqStatisticsApiV1DlqStatsGetResponse = GetDlqStatisticsApiV1DlqStatsGetResponses[keyof GetDlqStatisticsApiV1DlqStatsGetResponses];

export type GetDlqMessagesApiV1DlqMessagesGetData = {
    body?: never;
    path?: never;
    query?: {
        status?: DlqMessageStatus | null;
        topic?: string | null;
        event_type?: string | null;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/dlq/messages';
};

export type GetDlqMessagesApiV1DlqMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDlqMessagesApiV1DlqMessagesGetError = GetDlqMessagesApiV1DlqMessagesGetErrors[keyof GetDlqMessagesApiV1DlqMessagesGetErrors];

export type GetDlqMessagesApiV1DlqMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: DlqMessagesResponse;
};

export type GetDlqMessagesApiV1DlqMessagesGetResponse = GetDlqMessagesApiV1DlqMessagesGetResponses[keyof GetDlqMessagesApiV1DlqMessagesGetResponses];

export type DiscardDlqMessageApiV1DlqMessagesEventIdDeleteData = {
    body?: never;
    path: {
        event_id: string;
    };
    query: {
        /**
         * Reason for discarding
         */
        reason: string;
    };
    url: '/api/v1/dlq/messages/{event_id}';
};

export type DiscardDlqMessageApiV1DlqMessagesEventIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiscardDlqMessageApiV1DlqMessagesEventIdDeleteError = DiscardDlqMessageApiV1DlqMessagesEventIdDeleteErrors[keyof DiscardDlqMessageApiV1DlqMessagesEventIdDeleteErrors];

export type DiscardDlqMessageApiV1DlqMessagesEventIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DiscardDlqMessageApiV1DlqMessagesEventIdDeleteResponse = DiscardDlqMessageApiV1DlqMessagesEventIdDeleteResponses[keyof DiscardDlqMessageApiV1DlqMessagesEventIdDeleteResponses];

export type GetDlqMessageApiV1DlqMessagesEventIdGetData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/api/v1/dlq/messages/{event_id}';
};

export type GetDlqMessageApiV1DlqMessagesEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDlqMessageApiV1DlqMessagesEventIdGetError = GetDlqMessageApiV1DlqMessagesEventIdGetErrors[keyof GetDlqMessageApiV1DlqMessagesEventIdGetErrors];

export type GetDlqMessageApiV1DlqMessagesEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: DlqMessageDetail;
};

export type GetDlqMessageApiV1DlqMessagesEventIdGetResponse = GetDlqMessageApiV1DlqMessagesEventIdGetResponses[keyof GetDlqMessageApiV1DlqMessagesEventIdGetResponses];

export type RetryDlqMessagesApiV1DlqRetryPostData = {
    body: ManualRetryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/dlq/retry';
};

export type RetryDlqMessagesApiV1DlqRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryDlqMessagesApiV1DlqRetryPostError = RetryDlqMessagesApiV1DlqRetryPostErrors[keyof RetryDlqMessagesApiV1DlqRetryPostErrors];

export type RetryDlqMessagesApiV1DlqRetryPostResponses = {
    /**
     * Successful Response
     */
    200: DlqBatchRetryResponse;
};

export type RetryDlqMessagesApiV1DlqRetryPostResponse = RetryDlqMessagesApiV1DlqRetryPostResponses[keyof RetryDlqMessagesApiV1DlqRetryPostResponses];

export type SetRetryPolicyApiV1DlqRetryPolicyPostData = {
    body: RetryPolicyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/dlq/retry-policy';
};

export type SetRetryPolicyApiV1DlqRetryPolicyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRetryPolicyApiV1DlqRetryPolicyPostError = SetRetryPolicyApiV1DlqRetryPolicyPostErrors[keyof SetRetryPolicyApiV1DlqRetryPolicyPostErrors];

export type SetRetryPolicyApiV1DlqRetryPolicyPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type SetRetryPolicyApiV1DlqRetryPolicyPostResponse = SetRetryPolicyApiV1DlqRetryPolicyPostResponses[keyof SetRetryPolicyApiV1DlqRetryPolicyPostResponses];

export type GetDlqTopicsApiV1DlqTopicsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dlq/topics';
};

export type GetDlqTopicsApiV1DlqTopicsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DlqTopicSummaryResponse>;
};

export type GetDlqTopicsApiV1DlqTopicsGetResponse = GetDlqTopicsApiV1DlqTopicsGetResponses[keyof GetDlqTopicsApiV1DlqTopicsGetResponses];

export type NotificationStreamApiV1EventsNotificationsStreamGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events/notifications/stream';
};

export type NotificationStreamApiV1EventsNotificationsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExecutionEventsApiV1EventsExecutionsExecutionIdGetData = {
    body?: never;
    path: {
        execution_id: string;
    };
    query?: never;
    url: '/api/v1/events/executions/{execution_id}';
};

export type ExecutionEventsApiV1EventsExecutionsExecutionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecutionEventsApiV1EventsExecutionsExecutionIdGetError = ExecutionEventsApiV1EventsExecutionsExecutionIdGetErrors[keyof ExecutionEventsApiV1EventsExecutionsExecutionIdGetErrors];

export type ExecutionEventsApiV1EventsExecutionsExecutionIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SseHealthApiV1EventsHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events/health';
};

export type SseHealthApiV1EventsHealthGetResponses = {
    /**
     * Successful Response
     */
    200: SseHealthResponse;
};

export type SseHealthApiV1EventsHealthGetResponse = SseHealthApiV1EventsHealthGetResponses[keyof SseHealthApiV1EventsHealthGetResponses];

export type GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetData = {
    body?: never;
    path: {
        execution_id: string;
    };
    query?: {
        /**
         * Include system-generated events
         */
        include_system_events?: boolean;
    };
    url: '/api/v1/events/executions/{execution_id}/events';
};

export type GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetError = GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetErrors[keyof GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetErrors];

export type GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: EventListResponse;
};

export type GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetResponse = GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetResponses[keyof GetExecutionEventsApiV1EventsExecutionsExecutionIdEventsGetResponses];

export type GetUserEventsApiV1EventsUserGetData = {
    body?: never;
    path?: never;
    query?: {
        event_types?: Array<string> | null;
        start_time?: string | null;
        end_time?: string | null;
        limit?: number;
        skip?: number;
        sort_order?: SortOrder;
    };
    url: '/api/v1/events/user';
};

export type GetUserEventsApiV1EventsUserGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserEventsApiV1EventsUserGetError = GetUserEventsApiV1EventsUserGetErrors[keyof GetUserEventsApiV1EventsUserGetErrors];

export type GetUserEventsApiV1EventsUserGetResponses = {
    /**
     * Successful Response
     */
    200: EventListResponse;
};

export type GetUserEventsApiV1EventsUserGetResponse = GetUserEventsApiV1EventsUserGetResponses[keyof GetUserEventsApiV1EventsUserGetResponses];

export type QueryEventsApiV1EventsQueryPostData = {
    body: EventFilterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/events/query';
};

export type QueryEventsApiV1EventsQueryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryEventsApiV1EventsQueryPostError = QueryEventsApiV1EventsQueryPostErrors[keyof QueryEventsApiV1EventsQueryPostErrors];

export type QueryEventsApiV1EventsQueryPostResponses = {
    /**
     * Successful Response
     */
    200: EventListResponse;
};

export type QueryEventsApiV1EventsQueryPostResponse = QueryEventsApiV1EventsQueryPostResponses[keyof QueryEventsApiV1EventsQueryPostResponses];

export type GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetData = {
    body?: never;
    path: {
        correlation_id: string;
    };
    query?: {
        /**
         * Include events from all users (admin only)
         */
        include_all_users?: boolean;
        limit?: number;
    };
    url: '/api/v1/events/correlation/{correlation_id}';
};

export type GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetError = GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetErrors[keyof GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetErrors];

export type GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventListResponse;
};

export type GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetResponse = GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetResponses[keyof GetEventsByCorrelationApiV1EventsCorrelationCorrelationIdGetResponses];

export type GetCurrentRequestEventsApiV1EventsCurrentRequestGetData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/v1/events/current-request';
};

export type GetCurrentRequestEventsApiV1EventsCurrentRequestGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentRequestEventsApiV1EventsCurrentRequestGetError = GetCurrentRequestEventsApiV1EventsCurrentRequestGetErrors[keyof GetCurrentRequestEventsApiV1EventsCurrentRequestGetErrors];

export type GetCurrentRequestEventsApiV1EventsCurrentRequestGetResponses = {
    /**
     * Successful Response
     */
    200: EventListResponse;
};

export type GetCurrentRequestEventsApiV1EventsCurrentRequestGetResponse = GetCurrentRequestEventsApiV1EventsCurrentRequestGetResponses[keyof GetCurrentRequestEventsApiV1EventsCurrentRequestGetResponses];

export type GetEventStatisticsApiV1EventsStatisticsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start time for statistics (defaults to 24 hours ago)
         */
        start_time?: string | null;
        /**
         * End time for statistics (defaults to now)
         */
        end_time?: string | null;
        /**
         * Include stats from all users (admin only)
         */
        include_all_users?: boolean;
    };
    url: '/api/v1/events/statistics';
};

export type GetEventStatisticsApiV1EventsStatisticsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventStatisticsApiV1EventsStatisticsGetError = GetEventStatisticsApiV1EventsStatisticsGetErrors[keyof GetEventStatisticsApiV1EventsStatisticsGetErrors];

export type GetEventStatisticsApiV1EventsStatisticsGetResponses = {
    /**
     * Successful Response
     */
    200: EventStatistics;
};

export type GetEventStatisticsApiV1EventsStatisticsGetResponse = GetEventStatisticsApiV1EventsStatisticsGetResponses[keyof GetEventStatisticsApiV1EventsStatisticsGetResponses];

export type DeleteEventApiV1EventsEventIdDeleteData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/api/v1/events/{event_id}';
};

export type DeleteEventApiV1EventsEventIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEventApiV1EventsEventIdDeleteError = DeleteEventApiV1EventsEventIdDeleteErrors[keyof DeleteEventApiV1EventsEventIdDeleteErrors];

export type DeleteEventApiV1EventsEventIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteEventResponse;
};

export type DeleteEventApiV1EventsEventIdDeleteResponse = DeleteEventApiV1EventsEventIdDeleteResponses[keyof DeleteEventApiV1EventsEventIdDeleteResponses];

export type GetEventApiV1EventsEventIdGetData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/api/v1/events/{event_id}';
};

export type GetEventApiV1EventsEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventApiV1EventsEventIdGetError = GetEventApiV1EventsEventIdGetErrors[keyof GetEventApiV1EventsEventIdGetErrors];

export type GetEventApiV1EventsEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventResponse;
};

export type GetEventApiV1EventsEventIdGetResponse = GetEventApiV1EventsEventIdGetResponses[keyof GetEventApiV1EventsEventIdGetResponses];

export type PublishCustomEventApiV1EventsPublishPostData = {
    body: PublishEventRequest;
    path?: never;
    query?: never;
    url: '/api/v1/events/publish';
};

export type PublishCustomEventApiV1EventsPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishCustomEventApiV1EventsPublishPostError = PublishCustomEventApiV1EventsPublishPostErrors[keyof PublishCustomEventApiV1EventsPublishPostErrors];

export type PublishCustomEventApiV1EventsPublishPostResponses = {
    /**
     * Successful Response
     */
    200: PublishEventResponse;
};

export type PublishCustomEventApiV1EventsPublishPostResponse = PublishCustomEventApiV1EventsPublishPostResponses[keyof PublishCustomEventApiV1EventsPublishPostResponses];

export type AggregateEventsApiV1EventsAggregatePostData = {
    body: EventAggregationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/events/aggregate';
};

export type AggregateEventsApiV1EventsAggregatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AggregateEventsApiV1EventsAggregatePostError = AggregateEventsApiV1EventsAggregatePostErrors[keyof AggregateEventsApiV1EventsAggregatePostErrors];

export type AggregateEventsApiV1EventsAggregatePostResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type AggregateEventsApiV1EventsAggregatePostResponse = AggregateEventsApiV1EventsAggregatePostResponses[keyof AggregateEventsApiV1EventsAggregatePostResponses];

export type ListEventTypesApiV1EventsTypesListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events/types/list';
};

export type ListEventTypesApiV1EventsTypesListGetResponses = {
    /**
     * Successful Response
     */
    200: Array<string>;
};

export type ListEventTypesApiV1EventsTypesListGetResponse = ListEventTypesApiV1EventsTypesListGetResponses[keyof ListEventTypesApiV1EventsTypesListGetResponses];

export type ReplayAggregateEventsApiV1EventsReplayAggregateIdPostData = {
    body?: never;
    path: {
        aggregate_id: string;
    };
    query?: {
        /**
         * Service to replay events to
         */
        target_service?: string | null;
        /**
         * If true, only show what would be replayed
         */
        dry_run?: boolean;
    };
    url: '/api/v1/events/replay/{aggregate_id}';
};

export type ReplayAggregateEventsApiV1EventsReplayAggregateIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplayAggregateEventsApiV1EventsReplayAggregateIdPostError = ReplayAggregateEventsApiV1EventsReplayAggregateIdPostErrors[keyof ReplayAggregateEventsApiV1EventsReplayAggregateIdPostErrors];

export type ReplayAggregateEventsApiV1EventsReplayAggregateIdPostResponses = {
    /**
     * Successful Response
     */
    200: ReplayAggregateResponse;
};

export type ReplayAggregateEventsApiV1EventsReplayAggregateIdPostResponse = ReplayAggregateEventsApiV1EventsReplayAggregateIdPostResponses[keyof ReplayAggregateEventsApiV1EventsReplayAggregateIdPostResponses];

export type BrowseEventsApiV1AdminEventsBrowsePostData = {
    body: EventBrowseRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/events/browse';
};

export type BrowseEventsApiV1AdminEventsBrowsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrowseEventsApiV1AdminEventsBrowsePostError = BrowseEventsApiV1AdminEventsBrowsePostErrors[keyof BrowseEventsApiV1AdminEventsBrowsePostErrors];

export type BrowseEventsApiV1AdminEventsBrowsePostResponses = {
    /**
     * Successful Response
     */
    200: EventBrowseResponse;
};

export type BrowseEventsApiV1AdminEventsBrowsePostResponse = BrowseEventsApiV1AdminEventsBrowsePostResponses[keyof BrowseEventsApiV1AdminEventsBrowsePostResponses];

export type GetEventStatsApiV1AdminEventsStatsGetData = {
    body?: never;
    path?: never;
    query?: {
        hours?: number;
    };
    url: '/api/v1/admin/events/stats';
};

export type GetEventStatsApiV1AdminEventsStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventStatsApiV1AdminEventsStatsGetError = GetEventStatsApiV1AdminEventsStatsGetErrors[keyof GetEventStatsApiV1AdminEventsStatsGetErrors];

export type GetEventStatsApiV1AdminEventsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: EventStatsResponse;
};

export type GetEventStatsApiV1AdminEventsStatsGetResponse = GetEventStatsApiV1AdminEventsStatsGetResponses[keyof GetEventStatsApiV1AdminEventsStatsGetResponses];

export type DeleteEventApiV1AdminEventsEventIdDeleteData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/api/v1/admin/events/{event_id}';
};

export type DeleteEventApiV1AdminEventsEventIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEventApiV1AdminEventsEventIdDeleteError = DeleteEventApiV1AdminEventsEventIdDeleteErrors[keyof DeleteEventApiV1AdminEventsEventIdDeleteErrors];

export type DeleteEventApiV1AdminEventsEventIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: EventDeleteResponse;
};

export type DeleteEventApiV1AdminEventsEventIdDeleteResponse = DeleteEventApiV1AdminEventsEventIdDeleteResponses[keyof DeleteEventApiV1AdminEventsEventIdDeleteResponses];

export type GetEventDetailApiV1AdminEventsEventIdGetData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/api/v1/admin/events/{event_id}';
};

export type GetEventDetailApiV1AdminEventsEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventDetailApiV1AdminEventsEventIdGetError = GetEventDetailApiV1AdminEventsEventIdGetErrors[keyof GetEventDetailApiV1AdminEventsEventIdGetErrors];

export type GetEventDetailApiV1AdminEventsEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventDetailResponse;
};

export type GetEventDetailApiV1AdminEventsEventIdGetResponse = GetEventDetailApiV1AdminEventsEventIdGetResponses[keyof GetEventDetailApiV1AdminEventsEventIdGetResponses];

export type ReplayEventsApiV1AdminEventsReplayPostData = {
    body: EventReplayRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/events/replay';
};

export type ReplayEventsApiV1AdminEventsReplayPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplayEventsApiV1AdminEventsReplayPostError = ReplayEventsApiV1AdminEventsReplayPostErrors[keyof ReplayEventsApiV1AdminEventsReplayPostErrors];

export type ReplayEventsApiV1AdminEventsReplayPostResponses = {
    /**
     * Successful Response
     */
    200: EventReplayResponse;
};

export type ReplayEventsApiV1AdminEventsReplayPostResponse = ReplayEventsApiV1AdminEventsReplayPostResponses[keyof ReplayEventsApiV1AdminEventsReplayPostResponses];

export type GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/admin/events/replay/{session_id}/status';
};

export type GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetError = GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetErrors[keyof GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetErrors];

export type GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: EventReplayStatusResponse;
};

export type GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetResponse = GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetResponses[keyof GetReplayStatusApiV1AdminEventsReplaySessionIdStatusGetResponses];

export type ExportEventsCsvApiV1AdminEventsExportCsvGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Event types (repeat param for multiple)
         */
        event_types?: Array<EventType> | null;
        /**
         * Start time
         */
        start_time?: string | null;
        /**
         * End time
         */
        end_time?: string | null;
        limit?: number;
    };
    url: '/api/v1/admin/events/export/csv';
};

export type ExportEventsCsvApiV1AdminEventsExportCsvGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportEventsCsvApiV1AdminEventsExportCsvGetError = ExportEventsCsvApiV1AdminEventsExportCsvGetErrors[keyof ExportEventsCsvApiV1AdminEventsExportCsvGetErrors];

export type ExportEventsCsvApiV1AdminEventsExportCsvGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportEventsJsonApiV1AdminEventsExportJsonGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Event types (repeat param for multiple)
         */
        event_types?: Array<EventType> | null;
        /**
         * Aggregate ID filter
         */
        aggregate_id?: string | null;
        /**
         * Correlation ID filter
         */
        correlation_id?: string | null;
        /**
         * User ID filter
         */
        user_id?: string | null;
        /**
         * Service name filter
         */
        service_name?: string | null;
        /**
         * Start time
         */
        start_time?: string | null;
        /**
         * End time
         */
        end_time?: string | null;
        limit?: number;
    };
    url: '/api/v1/admin/events/export/json';
};

export type ExportEventsJsonApiV1AdminEventsExportJsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportEventsJsonApiV1AdminEventsExportJsonGetError = ExportEventsJsonApiV1AdminEventsExportJsonGetErrors[keyof ExportEventsJsonApiV1AdminEventsExportJsonGetErrors];

export type ExportEventsJsonApiV1AdminEventsExportJsonGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSystemSettingsApiV1AdminSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/settings/';
};

export type GetSystemSettingsApiV1AdminSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: SystemSettings;
};

export type GetSystemSettingsApiV1AdminSettingsGetResponse = GetSystemSettingsApiV1AdminSettingsGetResponses[keyof GetSystemSettingsApiV1AdminSettingsGetResponses];

export type UpdateSystemSettingsApiV1AdminSettingsPutData = {
    body: SystemSettings;
    path?: never;
    query?: never;
    url: '/api/v1/admin/settings/';
};

export type UpdateSystemSettingsApiV1AdminSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSystemSettingsApiV1AdminSettingsPutError = UpdateSystemSettingsApiV1AdminSettingsPutErrors[keyof UpdateSystemSettingsApiV1AdminSettingsPutErrors];

export type UpdateSystemSettingsApiV1AdminSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: SystemSettings;
};

export type UpdateSystemSettingsApiV1AdminSettingsPutResponse = UpdateSystemSettingsApiV1AdminSettingsPutResponses[keyof UpdateSystemSettingsApiV1AdminSettingsPutResponses];

export type ResetSystemSettingsApiV1AdminSettingsResetPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/settings/reset';
};

export type ResetSystemSettingsApiV1AdminSettingsResetPostResponses = {
    /**
     * Successful Response
     */
    200: SystemSettings;
};

export type ResetSystemSettingsApiV1AdminSettingsResetPostResponse = ResetSystemSettingsApiV1AdminSettingsResetPostResponses[keyof ResetSystemSettingsApiV1AdminSettingsResetPostResponses];

export type ListUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string | null;
        role?: UserRole | null;
    };
    url: '/api/v1/admin/users/';
};

export type ListUsersApiV1AdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiV1AdminUsersGetError = ListUsersApiV1AdminUsersGetErrors[keyof ListUsersApiV1AdminUsersGetErrors];

export type ListUsersApiV1AdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type ListUsersApiV1AdminUsersGetResponse = ListUsersApiV1AdminUsersGetResponses[keyof ListUsersApiV1AdminUsersGetResponses];

export type CreateUserApiV1AdminUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users/';
};

export type CreateUserApiV1AdminUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AdminUsersPostError = CreateUserApiV1AdminUsersPostErrors[keyof CreateUserApiV1AdminUsersPostErrors];

export type CreateUserApiV1AdminUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserApiV1AdminUsersPostResponse = CreateUserApiV1AdminUsersPostResponses[keyof CreateUserApiV1AdminUsersPostResponses];

export type DeleteUserApiV1AdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: {
        /**
         * Cascade delete user's data
         */
        cascade?: boolean;
    };
    url: '/api/v1/admin/users/{user_id}';
};

export type DeleteUserApiV1AdminUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteError = DeleteUserApiV1AdminUsersUserIdDeleteErrors[keyof DeleteUserApiV1AdminUsersUserIdDeleteErrors];

export type DeleteUserApiV1AdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteUserApiV1AdminUsersUserIdDeleteResponse = DeleteUserApiV1AdminUsersUserIdDeleteResponses[keyof DeleteUserApiV1AdminUsersUserIdDeleteResponses];

export type GetUserApiV1AdminUsersUserIdGetData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type GetUserApiV1AdminUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiV1AdminUsersUserIdGetError = GetUserApiV1AdminUsersUserIdGetErrors[keyof GetUserApiV1AdminUsersUserIdGetErrors];

export type GetUserApiV1AdminUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserApiV1AdminUsersUserIdGetResponse = GetUserApiV1AdminUsersUserIdGetResponses[keyof GetUserApiV1AdminUsersUserIdGetResponses];

export type UpdateUserApiV1AdminUsersUserIdPutData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type UpdateUserApiV1AdminUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1AdminUsersUserIdPutError = UpdateUserApiV1AdminUsersUserIdPutErrors[keyof UpdateUserApiV1AdminUsersUserIdPutErrors];

export type UpdateUserApiV1AdminUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserApiV1AdminUsersUserIdPutResponse = UpdateUserApiV1AdminUsersUserIdPutResponses[keyof UpdateUserApiV1AdminUsersUserIdPutResponses];

export type GetUserOverviewApiV1AdminUsersUserIdOverviewGetData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/overview';
};

export type GetUserOverviewApiV1AdminUsersUserIdOverviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserOverviewApiV1AdminUsersUserIdOverviewGetError = GetUserOverviewApiV1AdminUsersUserIdOverviewGetErrors[keyof GetUserOverviewApiV1AdminUsersUserIdOverviewGetErrors];

export type GetUserOverviewApiV1AdminUsersUserIdOverviewGetResponses = {
    /**
     * Successful Response
     */
    200: AdminUserOverview;
};

export type GetUserOverviewApiV1AdminUsersUserIdOverviewGetResponse = GetUserOverviewApiV1AdminUsersUserIdOverviewGetResponses[keyof GetUserOverviewApiV1AdminUsersUserIdOverviewGetResponses];

export type ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostData = {
    body: PasswordResetRequest;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/reset-password';
};

export type ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostError = ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostErrors[keyof ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostErrors];

export type ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostResponse = ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostResponses[keyof ResetUserPasswordApiV1AdminUsersUserIdResetPasswordPostResponses];

export type GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/rate-limits';
};

export type GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetError = GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetErrors[keyof GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetErrors];

export type GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetResponse = GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetResponses[keyof GetUserRateLimitsApiV1AdminUsersUserIdRateLimitsGetResponses];

export type UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutData = {
    body: UserRateLimit;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/rate-limits';
};

export type UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutError = UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutErrors[keyof UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutErrors];

export type UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutResponse = UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutResponses[keyof UpdateUserRateLimitsApiV1AdminUsersUserIdRateLimitsPutResponses];

export type ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/rate-limits/reset';
};

export type ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostError = ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostErrors[keyof ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostErrors];

export type ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostResponse = ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostResponses[keyof ResetUserRateLimitsApiV1AdminUsersUserIdRateLimitsResetPostResponses];

export type GetUserSettingsApiV1UserSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/settings/';
};

export type GetUserSettingsApiV1UserSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type GetUserSettingsApiV1UserSettingsGetResponse = GetUserSettingsApiV1UserSettingsGetResponses[keyof GetUserSettingsApiV1UserSettingsGetResponses];

export type UpdateUserSettingsApiV1UserSettingsPutData = {
    body: UserSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/user/settings/';
};

export type UpdateUserSettingsApiV1UserSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserSettingsApiV1UserSettingsPutError = UpdateUserSettingsApiV1UserSettingsPutErrors[keyof UpdateUserSettingsApiV1UserSettingsPutErrors];

export type UpdateUserSettingsApiV1UserSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UpdateUserSettingsApiV1UserSettingsPutResponse = UpdateUserSettingsApiV1UserSettingsPutResponses[keyof UpdateUserSettingsApiV1UserSettingsPutResponses];

export type UpdateThemeApiV1UserSettingsThemePutData = {
    body: ThemeUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user/settings/theme';
};

export type UpdateThemeApiV1UserSettingsThemePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateThemeApiV1UserSettingsThemePutError = UpdateThemeApiV1UserSettingsThemePutErrors[keyof UpdateThemeApiV1UserSettingsThemePutErrors];

export type UpdateThemeApiV1UserSettingsThemePutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UpdateThemeApiV1UserSettingsThemePutResponse = UpdateThemeApiV1UserSettingsThemePutResponses[keyof UpdateThemeApiV1UserSettingsThemePutResponses];

export type UpdateNotificationSettingsApiV1UserSettingsNotificationsPutData = {
    body: NotificationSettings;
    path?: never;
    query?: never;
    url: '/api/v1/user/settings/notifications';
};

export type UpdateNotificationSettingsApiV1UserSettingsNotificationsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNotificationSettingsApiV1UserSettingsNotificationsPutError = UpdateNotificationSettingsApiV1UserSettingsNotificationsPutErrors[keyof UpdateNotificationSettingsApiV1UserSettingsNotificationsPutErrors];

export type UpdateNotificationSettingsApiV1UserSettingsNotificationsPutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UpdateNotificationSettingsApiV1UserSettingsNotificationsPutResponse = UpdateNotificationSettingsApiV1UserSettingsNotificationsPutResponses[keyof UpdateNotificationSettingsApiV1UserSettingsNotificationsPutResponses];

export type UpdateEditorSettingsApiV1UserSettingsEditorPutData = {
    body: EditorSettings;
    path?: never;
    query?: never;
    url: '/api/v1/user/settings/editor';
};

export type UpdateEditorSettingsApiV1UserSettingsEditorPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEditorSettingsApiV1UserSettingsEditorPutError = UpdateEditorSettingsApiV1UserSettingsEditorPutErrors[keyof UpdateEditorSettingsApiV1UserSettingsEditorPutErrors];

export type UpdateEditorSettingsApiV1UserSettingsEditorPutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UpdateEditorSettingsApiV1UserSettingsEditorPutResponse = UpdateEditorSettingsApiV1UserSettingsEditorPutResponses[keyof UpdateEditorSettingsApiV1UserSettingsEditorPutResponses];

export type GetSettingsHistoryApiV1UserSettingsHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/v1/user/settings/history';
};

export type GetSettingsHistoryApiV1UserSettingsHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSettingsHistoryApiV1UserSettingsHistoryGetError = GetSettingsHistoryApiV1UserSettingsHistoryGetErrors[keyof GetSettingsHistoryApiV1UserSettingsHistoryGetErrors];

export type GetSettingsHistoryApiV1UserSettingsHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: SettingsHistoryResponse;
};

export type GetSettingsHistoryApiV1UserSettingsHistoryGetResponse = GetSettingsHistoryApiV1UserSettingsHistoryGetResponses[keyof GetSettingsHistoryApiV1UserSettingsHistoryGetResponses];

export type RestoreSettingsApiV1UserSettingsRestorePostData = {
    body: RestoreSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user/settings/restore';
};

export type RestoreSettingsApiV1UserSettingsRestorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestoreSettingsApiV1UserSettingsRestorePostError = RestoreSettingsApiV1UserSettingsRestorePostErrors[keyof RestoreSettingsApiV1UserSettingsRestorePostErrors];

export type RestoreSettingsApiV1UserSettingsRestorePostResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type RestoreSettingsApiV1UserSettingsRestorePostResponse = RestoreSettingsApiV1UserSettingsRestorePostResponses[keyof RestoreSettingsApiV1UserSettingsRestorePostResponses];

export type UpdateCustomSettingApiV1UserSettingsCustomKeyPutData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        key: string;
    };
    query?: never;
    url: '/api/v1/user/settings/custom/{key}';
};

export type UpdateCustomSettingApiV1UserSettingsCustomKeyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCustomSettingApiV1UserSettingsCustomKeyPutError = UpdateCustomSettingApiV1UserSettingsCustomKeyPutErrors[keyof UpdateCustomSettingApiV1UserSettingsCustomKeyPutErrors];

export type UpdateCustomSettingApiV1UserSettingsCustomKeyPutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UpdateCustomSettingApiV1UserSettingsCustomKeyPutResponse = UpdateCustomSettingApiV1UserSettingsCustomKeyPutResponses[keyof UpdateCustomSettingApiV1UserSettingsCustomKeyPutResponses];

export type GetNotificationsApiV1NotificationsGetData = {
    body?: never;
    path?: never;
    query?: {
        status?: NotificationStatus | null;
        /**
         * Only notifications with any of these tags
         */
        include_tags?: Array<string> | null;
        /**
         * Exclude notifications with any of these tags
         */
        exclude_tags?: Array<string> | null;
        /**
         * Only notifications having a tag starting with this prefix
         */
        tag_prefix?: string | null;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/notifications';
};

export type GetNotificationsApiV1NotificationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotificationsApiV1NotificationsGetError = GetNotificationsApiV1NotificationsGetErrors[keyof GetNotificationsApiV1NotificationsGetErrors];

export type GetNotificationsApiV1NotificationsGetResponses = {
    /**
     * Successful Response
     */
    200: NotificationListResponse;
};

export type GetNotificationsApiV1NotificationsGetResponse = GetNotificationsApiV1NotificationsGetResponses[keyof GetNotificationsApiV1NotificationsGetResponses];

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutData = {
    body?: never;
    path: {
        notification_id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{notification_id}/read';
};

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutError = MarkNotificationReadApiV1NotificationsNotificationIdReadPutErrors[keyof MarkNotificationReadApiV1NotificationsNotificationIdReadPutErrors];

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutResponse = MarkNotificationReadApiV1NotificationsNotificationIdReadPutResponses[keyof MarkNotificationReadApiV1NotificationsNotificationIdReadPutResponses];

export type MarkAllReadApiV1NotificationsMarkAllReadPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/mark-all-read';
};

export type MarkAllReadApiV1NotificationsMarkAllReadPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MarkAllReadApiV1NotificationsMarkAllReadPostResponse = MarkAllReadApiV1NotificationsMarkAllReadPostResponses[keyof MarkAllReadApiV1NotificationsMarkAllReadPostResponses];

export type GetSubscriptionsApiV1NotificationsSubscriptionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/subscriptions';
};

export type GetSubscriptionsApiV1NotificationsSubscriptionsGetResponses = {
    /**
     * Successful Response
     */
    200: SubscriptionsResponse;
};

export type GetSubscriptionsApiV1NotificationsSubscriptionsGetResponse = GetSubscriptionsApiV1NotificationsSubscriptionsGetResponses[keyof GetSubscriptionsApiV1NotificationsSubscriptionsGetResponses];

export type UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutData = {
    body: SubscriptionUpdate;
    path: {
        channel: NotificationChannel;
    };
    query?: never;
    url: '/api/v1/notifications/subscriptions/{channel}';
};

export type UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutError = UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutErrors[keyof UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutErrors];

export type UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutResponses = {
    /**
     * Successful Response
     */
    200: NotificationSubscription;
};

export type UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutResponse = UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutResponses[keyof UpdateSubscriptionApiV1NotificationsSubscriptionsChannelPutResponses];

export type GetUnreadCountApiV1NotificationsUnreadCountGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/unread-count';
};

export type GetUnreadCountApiV1NotificationsUnreadCountGetResponses = {
    /**
     * Successful Response
     */
    200: UnreadCountResponse;
};

export type GetUnreadCountApiV1NotificationsUnreadCountGetResponse = GetUnreadCountApiV1NotificationsUnreadCountGetResponses[keyof GetUnreadCountApiV1NotificationsUnreadCountGetResponses];

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteData = {
    body?: never;
    path: {
        notification_id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{notification_id}';
};

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteError = DeleteNotificationApiV1NotificationsNotificationIdDeleteErrors[keyof DeleteNotificationApiV1NotificationsNotificationIdDeleteErrors];

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteNotificationResponse;
};

export type DeleteNotificationApiV1NotificationsNotificationIdDeleteResponse = DeleteNotificationApiV1NotificationsNotificationIdDeleteResponses[keyof DeleteNotificationApiV1NotificationsNotificationIdDeleteResponses];

export type GetSagaStatusApiV1SagasSagaIdGetData = {
    body?: never;
    path: {
        saga_id: string;
    };
    query?: never;
    url: '/api/v1/sagas/{saga_id}';
};

export type GetSagaStatusApiV1SagasSagaIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSagaStatusApiV1SagasSagaIdGetError = GetSagaStatusApiV1SagasSagaIdGetErrors[keyof GetSagaStatusApiV1SagasSagaIdGetErrors];

export type GetSagaStatusApiV1SagasSagaIdGetResponses = {
    /**
     * Successful Response
     */
    200: SagaStatusResponse;
};

export type GetSagaStatusApiV1SagasSagaIdGetResponse = GetSagaStatusApiV1SagasSagaIdGetResponses[keyof GetSagaStatusApiV1SagasSagaIdGetResponses];

export type GetExecutionSagasApiV1SagasExecutionExecutionIdGetData = {
    body?: never;
    path: {
        execution_id: string;
    };
    query?: {
        /**
         * Filter by saga state
         */
        state?: SagaState | null;
    };
    url: '/api/v1/sagas/execution/{execution_id}';
};

export type GetExecutionSagasApiV1SagasExecutionExecutionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExecutionSagasApiV1SagasExecutionExecutionIdGetError = GetExecutionSagasApiV1SagasExecutionExecutionIdGetErrors[keyof GetExecutionSagasApiV1SagasExecutionExecutionIdGetErrors];

export type GetExecutionSagasApiV1SagasExecutionExecutionIdGetResponses = {
    /**
     * Successful Response
     */
    200: SagaListResponse;
};

export type GetExecutionSagasApiV1SagasExecutionExecutionIdGetResponse = GetExecutionSagasApiV1SagasExecutionExecutionIdGetResponses[keyof GetExecutionSagasApiV1SagasExecutionExecutionIdGetResponses];

export type ListSagasApiV1SagasGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by saga state
         */
        state?: SagaState | null;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/sagas/';
};

export type ListSagasApiV1SagasGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSagasApiV1SagasGetError = ListSagasApiV1SagasGetErrors[keyof ListSagasApiV1SagasGetErrors];

export type ListSagasApiV1SagasGetResponses = {
    /**
     * Successful Response
     */
    200: SagaListResponse;
};

export type ListSagasApiV1SagasGetResponse = ListSagasApiV1SagasGetResponses[keyof ListSagasApiV1SagasGetResponses];

export type CancelSagaApiV1SagasSagaIdCancelPostData = {
    body?: never;
    path: {
        saga_id: string;
    };
    query?: never;
    url: '/api/v1/sagas/{saga_id}/cancel';
};

export type CancelSagaApiV1SagasSagaIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelSagaApiV1SagasSagaIdCancelPostError = CancelSagaApiV1SagasSagaIdCancelPostErrors[keyof CancelSagaApiV1SagasSagaIdCancelPostErrors];

export type CancelSagaApiV1SagasSagaIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: SagaCancellationResponse;
};

export type CancelSagaApiV1SagasSagaIdCancelPostResponse = CancelSagaApiV1SagasSagaIdCancelPostResponses[keyof CancelSagaApiV1SagasSagaIdCancelPostResponses];

export type ReceiveGrafanaAlertsApiV1AlertsGrafanaPostData = {
    body: GrafanaWebhook;
    path?: never;
    query?: never;
    url: '/api/v1/alerts/grafana';
};

export type ReceiveGrafanaAlertsApiV1AlertsGrafanaPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveGrafanaAlertsApiV1AlertsGrafanaPostError = ReceiveGrafanaAlertsApiV1AlertsGrafanaPostErrors[keyof ReceiveGrafanaAlertsApiV1AlertsGrafanaPostErrors];

export type ReceiveGrafanaAlertsApiV1AlertsGrafanaPostResponses = {
    /**
     * Successful Response
     */
    200: AlertResponse;
};

export type ReceiveGrafanaAlertsApiV1AlertsGrafanaPostResponse = ReceiveGrafanaAlertsApiV1AlertsGrafanaPostResponses[keyof ReceiveGrafanaAlertsApiV1AlertsGrafanaPostResponses];

export type TestGrafanaAlertEndpointApiV1AlertsGrafanaTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/alerts/grafana/test';
};

export type TestGrafanaAlertEndpointApiV1AlertsGrafanaTestGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type TestGrafanaAlertEndpointApiV1AlertsGrafanaTestGetResponse = TestGrafanaAlertEndpointApiV1AlertsGrafanaTestGetResponses[keyof TestGrafanaAlertEndpointApiV1AlertsGrafanaTestGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};