version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/integr8scode
    depends_on:
      - mongo
    volumes:
      - ./kubeconfig.yaml:/app/kubeconfig.yaml:ro

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: