apiVersion: v1
kind: Config
clusters:
- name: docker-desktop
  cluster:
    server: https://kubernetes.docker.internal:6443
    insecure-skip-tls-verify: true
users:
- name: docker-desktop
  user:
    client-certificate-data: <certificate data>
    client-key-data: <key data>
contexts:
- name: docker-desktop
  context:
    cluster: docker-desktop
    user: docker-desktop
current-context: docker-desktop