name: 'E2E Ready'
description: 'Finalize k3s, wait for infra, start compose stack, health-check, seed test users'

inputs:
  image-tag:
    description: 'GHCR image tag (e.g., sha-abc1234)'
    required: true
  wait-for-frontend:
    description: 'Also wait for frontend health check (default: false)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Finalize k3s
      shell: bash
      run: |
        mkdir -p /home/runner/.kube
        sudo k3s kubectl config view --raw > /home/runner/.kube/config
        sudo chmod 600 /home/runner/.kube/config
        export KUBECONFIG=/home/runner/.kube/config
        timeout 90 bash -c 'until kubectl cluster-info 2>/dev/null; do sleep 3; done'
        kubectl create namespace integr8scode --dry-run=client -o yaml | kubectl apply -f -
        sed -E 's#https://(127\.0\.0\.1|0\.0\.0\.0):6443#https://host.docker.internal:6443#g' \
          /home/runner/.kube/config > backend/kubeconfig.yaml
        chmod 644 backend/kubeconfig.yaml

    - name: Use test environment config
      shell: bash
      run: |
        cp backend/config.test.toml backend/config.toml
        cp backend/secrets.example.toml backend/secrets.toml

    - name: Pre-pull test runtime image into K3s
      shell: bash
      run: sudo k3s ctr images pull docker.io/library/python:3.11-slim

    - name: Wait for image pull and infra
      shell: bash
      run: |
        if [ -f /tmp/infra-pull.pid ]; then
          PID=$(cat /tmp/infra-pull.pid)
          if kill -0 "$PID" 2>/dev/null; then
            echo "Waiting for image pull + infra startup..."
            tail --pid="$PID" -f /dev/null 2>/dev/null || true
          fi
        fi
        cat /tmp/infra-pull.log 2>/dev/null || true
        if [ -f /tmp/infra-pull.exit ]; then
          EXIT_CODE=$(cat /tmp/infra-pull.exit)
          if [ "$EXIT_CODE" != "0" ]; then
            echo "::error::Background image pull / infra pre-warm failed (exit $EXIT_CODE)"
            exit 1
          fi
        fi

    - name: Start stack
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: docker compose up -d --no-build

    - name: Wait for services
      shell: bash
      env:
        WAIT_FOR_FRONTEND: ${{ inputs.wait-for-frontend }}
      run: |
        echo "Waiting for backend health..."
        timeout 120 bash -c 'until curl -ksf https://localhost/api/v1/health/live 2>/dev/null; do sleep 2; done'
        echo "Backend ready"
        if [ "$WAIT_FOR_FRONTEND" = "true" ]; then
          echo "Waiting for frontend health..."
          timeout 60 bash -c 'until curl -ksf https://localhost:5001 2>/dev/null; do sleep 2; done'
          echo "Frontend ready"
        fi

    - name: Seed test users
      shell: bash
      run: docker compose exec -T backend uv run python scripts/seed_users.py
