apiVersion: 1
policies:
  - orgId: 1
    receiver: grafana-internal-am   # <- new default
    group_by: [grafana_folder, alertname]
    group_wait:      30s
    group_interval:  5m
    repeat_interval: 4h
