global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      match_re:
        alertname: '(NetworkPolicyViolations|PrivilegeEscalationAttempts|CriticalMemoryUtilization|CriticalCPUUtilization)'
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m
      receiver: 'critical-security'

    - match:
        severity: critical
      group_wait: 15s
      group_interval: 2m
      repeat_interval: 1h
      receiver: 'critical-infrastructure'

    - match:
        severity: warning
      group_wait: 1m
      group_interval: 10m
      repeat_interval: 6h
      receiver: 'warning'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:443/api/v1/health'
        send_resolved: true
        title: 'Integr8sCode Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'critical-security'
    webhook_configs:
      - url: 'http://backend:443/api/v1/health'
        send_resolved: true
        title: '🚨 CRITICAL SECURITY ALERT: {{ .GroupLabels.alertname }}'
        text: |
          IMMEDIATE ATTENTION REQUIRED - Security incident detected!
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-infrastructure'
    webhook_configs:
      - url: 'http://backend:443/api/v1/health'
        send_resolved: true
        title: '🔥 CRITICAL INFRASTRUCTURE ALERT: {{ .GroupLabels.alertname }}'
        text: |
          Critical system issue requiring immediate attention!
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'warning'
    webhook_configs:
      - url: 'http://backend:443/api/v1/health'
        send_resolved: true
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          Warning condition detected - monitoring recommended.
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}