global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      match_re:
        alertname: '(NetworkPolicyViolations|PrivilegeEscalationAttempts|CriticalMemoryUtilization|CriticalCPUUtilization)'
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m
      receiver: 'critical-security'

    - match:
        severity: critical
      group_wait: 15s
      group_interval: 2m
      repeat_interval: 1h
      receiver: 'critical-infrastructure'

    - match:
        severity: warning
      group_wait: 1m
      group_interval: 10m
      repeat_interval: 6h
      receiver: 'warning'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'https://backend:443/api/v1/alertmanager/webhook'
        send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true  # Accept self-signed certificates for local development

  - name: 'critical-security'
    webhook_configs:
      - url: 'https://backend:443/api/v1/alertmanager/webhook'
        send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true  # Accept self-signed certificates for local development

  - name: 'critical-infrastructure'
    webhook_configs:
      - url: 'https://backend:443/api/v1/alertmanager/webhook'
        send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true  # Accept self-signed certificates for local development

  - name: 'warning'
    webhook_configs:
      - url: 'https://backend:443/api/v1/alertmanager/webhook'
        send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true  # Accept self-signed certificates for local development