name: 'K3s Setup'
description: 'Install k3s and create kubeconfig for Docker containers'

inputs:
  namespace:
    description: 'Kubernetes namespace to create'
    required: false
    default: 'integr8scode'
  kubeconfig-path:
    description: 'Path to write the Docker-accessible kubeconfig'
    required: false
    default: 'backend/kubeconfig.yaml'

outputs:
  kubeconfig:
    description: 'Path to the kubeconfig file for Docker containers'
    value: ${{ inputs.kubeconfig-path }}

runs:
  using: 'composite'
  steps:
    - name: Install k3s
      shell: bash
      run: |
        # --bind-address 0.0.0.0: Listen on all interfaces so Docker containers can reach it
        # --tls-san host.docker.internal: Include in cert SANs for Docker container access
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik --bind-address 0.0.0.0 --tls-san host.docker.internal" sh -
        mkdir -p /home/runner/.kube
        sudo k3s kubectl config view --raw > /home/runner/.kube/config
        sudo chmod 600 /home/runner/.kube/config

    - name: Wait for k3s to be ready
      shell: bash
      run: |
        export KUBECONFIG=/home/runner/.kube/config
        timeout 90 bash -c 'until kubectl cluster-info; do sleep 5; done'

    - name: Create namespace
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
      run: |
        export KUBECONFIG=/home/runner/.kube/config
        kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

    - name: Create kubeconfig for Docker containers
      shell: bash
      env:
        KUBECONFIG_PATH: ${{ inputs.kubeconfig-path }}
      run: |
        # Replace localhost with host.docker.internal for container access
        sed 's|https://127.0.0.1:6443|https://host.docker.internal:6443|g' \
          /home/runner/.kube/config > "$KUBECONFIG_PATH"
        chmod 644 "$KUBECONFIG_PATH"
        echo "Kubeconfig written to $KUBECONFIG_PATH"
