name: 'Docker Image Cache'
description: 'Cache and load Docker images for CI jobs'

inputs:
  images:
    description: 'Space-separated list of Docker images to cache'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate cache key from images
      id: cache-key
      shell: bash
      env:
        IMAGES_INPUT: ${{ inputs.images }}
      run: |
        # Create a stable hash from the sorted image list
        # Using env var to prevent script injection
        IMAGES_HASH=$(echo "$IMAGES_INPUT" | tr ' ' '\n' | sort | md5sum | cut -d' ' -f1)
        echo "key=docker-${{ runner.os }}-${IMAGES_HASH}" >> $GITHUB_OUTPUT

    - name: Cache Docker images
      uses: actions/cache@v5
      id: docker-cache
      with:
        path: /tmp/docker-cache
        key: ${{ steps.cache-key.outputs.key }}

    - name: Load cached Docker images
      if: steps.docker-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "Loading cached images..."
        for f in /tmp/docker-cache/*.tar.zst; do
          zstd -d -c "$f" | docker load &
        done
        wait
        docker images

    - name: Pull and save Docker images
      if: steps.docker-cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        IMAGES_INPUT: ${{ inputs.images }}
      run: |
        mkdir -p /tmp/docker-cache

        echo "Pulling images in parallel..."
        for img in $IMAGES_INPUT; do
          docker pull "$img" &
        done
        wait

        echo "Saving images with zstd compression..."
        for img in $IMAGES_INPUT; do
          # Create filename from image name (replace special chars)
          filename=$(echo "$img" | tr '/:' '_')
          docker save "$img" | zstd -T0 -3 > "/tmp/docker-cache/${filename}.tar.zst" &
        done
        wait

        echo "Cache size:"
        du -sh /tmp/docker-cache/
